### ISSUE TITLE
Avoid using the exported variables inside of a Bash function

### ISSUE THREAD

**Issue by LozanoMatheus** [aws-samples/ssm-agent-daemonset-installer#1]
### Avoid using the exported variables inside of a Bash function

When you use a variable like this `VAR=value`, Bash will declare this function as an exported variable and it can be accessed from any part of the script and by the subprocess (e.g. loading another Bash script inside of the `runonce.sh`). In the script [runonce.sh](../blob/ab17e98e1c02f0b45544eedb90353a4ece70c374/runonce.sh), it will first declare the `PODS` variable in the function [wait_for_pods](../blob/ab17e98e1c02f0b45544eedb90353a4ece70c374/runonce.sh#L18) then it will override the same variable in the function [wait_for_success](../blob/ab17e98e1c02f0b45544eedb90353a4ece70c374/runonce.sh#L33). I wrote an article about the Bash variables scope, you can check it [in here](https://medium.com/unboxing-the-cloud/bash-variables-things-that-you-probably-dont-know-about-it-8a5470887331?sk=26693ca772a0c54c99d3712303560ed4).

In my case, I usually load bash scripts in the CI/CD pipelines then execute the functions. In this case, the exported variable `PODS` will cause some an issue for other scripts, because it will already be defined.

You can define the PODS variable to be read-only by using `-r`.

It's also not a good practice to define a variable like that.

**Comment by jicowan** [comment]
@LozanoMatheus The daemonset-installer can now be installed by applying setup.yaml. Do you think this PR is still needed?
